
ARG BASE_IMAGE=nansencenter/nansat_base:latest-slim
FROM ${BASE_IMAGE}

RUN pip install --no-cache-dir \
    setuptools \
    wheel

RUN python -c 'import pythesint; pythesint.update_all_vocabularies()'

WORKDIR /src
